# Netlify configuration file

[build]
  base = "src/client"
  publish = "dist"
  command = "npm run build"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API requests to the backend server
[[redirects]]
  from = "/api/*"
  to = "https://health-buddy-api.herokuapp.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}